### PR TITLE
Address Issue #7 and misc other improvements

### PR DESCRIPTION
**Pull request by c-suh**
1.  Correct implementation of configurable font size for Feedback tab ([#7](https://github.com/NASA-PDS-Incubator/feedback-widget/issues/7)).
1.1 Update README.md that tab's icon remains with setting of font size.
2.  Remove redundant reCAPTCHA links from Feedback footer.
3.  Fix behavior of Feedback body on reCAPTCHA error.

### CODE REVIEW

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
@c-suh is this deployed somewhere?

**Comment by c-suh** [comment]
Yes, on PDS' gamma site (just implemented) and PDS Engineering's gamma site (DM for the path to the directory where the configuration file is housed). A clear cache and hard refresh may be needed to see the changes.

**Comment by jordanpadams** [comment]
@c-suh  I just got this error?

Screen Shot 2019-09-06 at 2 43 16 PM

**Comment by c-suh** [comment]
I just got the same on PDS' gamma site but PDS Engineering's gamma site seems to have gone through. I will look into this and DM you shortly.

**Comment by c-suh** [comment]
Error mentioned above is part of another issue which is to be created.

**Pull request merged**
